version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.371
- serviceName: edge.dimatest7107.integrations:testflow
  packages:
  - name: EdgeDimaTest7107
    version: "1.0"
  - name: CommonUtils
    version: "1.0"
- serviceName: edge.dimatest7107.integrations:testflow2
  packages:
  - name: EdgeDimaTest7107
    version: "1.0"
  - name: CommonUtils
    version: "1.0"
- serviceName: edge.dimatest7107.integrations:testflow3
  packages:
  - name: EdgeDimaTest7107
    version: "1.0"
  - name: CommonUtils
    version: "1.0"
packages:
- name: EdgeDimaTest7107
  gitServerName: dima
  gitUrl: https://github.com/deemashlayer/EdgeDimaTest7107
  gitUsername: deemashlayer
  gitToken: edge.scaffolding.EdgeDimaTest7107.dima.gitToken
  gitBranch: master
- name: CommonUtils
  gitServerName: dima
  gitUrl: https://github.com/deemashlayer
  gitUsername: deemashlayer
  gitToken: edge.scaffolding.CommonUtils.dima.gitToken
  gitBranch: "1.0"
